export const projects = [
  {
    id: "01",
    name: "Sneakrz King",
    platform: "Next.js / Vercel",
    type: "E-Commerce — Sneaker Store",
    tags: ["React.js", "Next.js", "Tailwind CSS", "Vercel", "Responsive Design"],
    description:
      "A custom-built sneaker e-commerce platform deployed on Vercel. Features advanced product filtering by brand, real-time search, a dynamic shopping cart, and seamless social media integration with Instagram and WhatsApp.",
    metrics: "<1.2s Load Time",
    url: "https://sneakrz-king.vercel.app",
    images: ["/photos/king-1.png", "/photos/king-2.png"],
    features: [
      "Product display with images and details",
      "Filtering by brand",
      "Search functionality",
      "Shopping cart",
      "Responsive design",
      "Social media integration (Instagram, WhatsApp)",
    ],
    techStack: {
      frontend: ["React.js", "Next.js", "HTML5", "CSS3", "Tailwind CSS", "JavaScript"],
      backend: ["Node.js", "Serverless Functions"],
      database: ["NoSQL (MongoDB / Firebase)"],
      deployment: ["Vercel"],
    },
    skills: [
      "Frontend Development",
      "UI/UX Design",
      "API Integration",
      "State Management",
      "Responsive Web Design",
      "Version Control (Git)",
    ],
  },
  {
    id: "02",
    name: "Helwa Fashion",
    platform: "Shopify / Custom Theme",
    type: "E-Commerce — Fashion Store",
    tags: ["Shopify", "Liquid", "CSS3", "JavaScript", "SEO"],
    description:
      "A premium women's fashion Shopify store with a dark luxury theme. Includes promotional pop-ups, policy pages, account management, and deep integration with Facebook, Instagram, TikTok, and WhatsApp for marketing reach.",
    metrics: "+42% Conversion Rate",
    url: "https://helwafashion.com",
    images: ["/photos/helwa-1.png", "/photos/helwa-2.png"],
    features: [
      "Product display with prices and sale indicators",
      "Navigation menu (Home, Catalog, Contact)",
      "Search functionality",
      "Shopping cart",
      "Account management",
      "Promotional pop-up for discounts",
      "Social media integration (Facebook, Instagram, TikTok, WhatsApp)",
      "Policy pages (Refund, Shipping, Privacy)",
    ],
    techStack: {
      frontend: ["HTML5", "CSS3", "JavaScript", "Shopify Liquid"],
      backend: ["Shopify (Ruby on Rails)"],
      database: ["Shopify Integrated"],
      deployment: ["Shopify Hosting"],
    },
    skills: [
      "E-Commerce Platform Customization",
      "UI/UX Design",
      "Payment Gateway Integration",
      "SEO Best Practices",
      "Digital Marketing Integration",
      "Frontend Development",
    ],
  },
  {
    id: "03",
    name: "Djabi",
    platform: "Shopify / Modest Fashion",
    type: "E-Commerce — Modest Fashion Store",
    tags: ["Shopify", "Liquid", "UI/UX", "Content Management", "SEO"],
    description:
      "A complete e-commerce store for a modest fashion brand featuring the SUJOOD collection. Built with categorized product navigation (Prayer Isdals, Kaftans, Umara Abayas), email subscription for new arrivals, and full social media marketing integration.",
    metrics: "2x Organic Traffic",
    url: "https://djabi-eg.com",
    images: ["/photos/djabi-1.png", "/photos/djabi-2.png"],
    features: [
      "Product display with prices and sale indicators",
      "Categorized products (Prayer Isdals, Kaftans, Umara Abaya)",
      "Navigation menu",
      "Search functionality",
      "Shopping cart",
      "Account management",
      "Email subscription for new arrivals",
      "Social media integration (Facebook, Instagram, TikTok, WhatsApp)",
      "Policy pages (Privacy, Shipping, Refund, Terms of Service)",
    ],
    techStack: {
      frontend: ["HTML5", "CSS3", "JavaScript", "Shopify Liquid"],
      backend: ["Shopify (Ruby on Rails)"],
      database: ["Shopify Integrated"],
      deployment: ["Shopify Hosting"],
    },
    skills: [
      "E-Commerce Platform Management",
      "Product Catalog Management",
      "UI/UX Design",
      "Content Management",
      "Digital Marketing",
      "Frontend Development",
    ],
  },
];

export const experiences = [
  {
    role: "Freelance Full-Stack Developer",
    company: "Self Employed",
    year: "2024 — Present",
  },
  {
    role: "Network & Cyber Security Student",
    company: "ElSewedy University of Technology",
    year: "2023 — Present",
  },
];

export const skills = [
  "React",
  "TypeScript",
  "Next.js",
  "Three.js",
  "Tailwind CSS",
  "Shopify",
  "Node.js",
  "PostgreSQL",
  "Framer Motion",
  "Supabase",
];
